# Site settings
title: Your Website Title
description: A brief description of your website

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
